JKTasks/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views
from rest_framework import routers
app_name = "JKTasks"
urlpatterns = [
    path('', include('Tasks.urls')),
    path('tasks/', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='JKTasks/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('bot/', include('Telebot.urls')),
    path('cd/', include('countdown.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

Tasks/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "Tasks"
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^new-task/$', views.new_task, name='new_task'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<task_type>/', views.tasks, name='tasks'),
    path('task/<task_id>', views.task, name='task'),
    path('task/delete/<task_id>', views.task_delete, name='task_delete'),
    path('notes/', views.notes, name='notes'),
    path('notes/new', views.new_note, name='new_note'),
    path('notes/<note_id>', views.note, name='note'),
    path('manage/', views.task_management, name='task_management'),
    path('temp/', views.temp, name='temp'),
    path('temp_data/', views.temp_data, name='temp_data'),
    path('api/tasks', views.TaskViewSet.as_view({'get': 'list'}), name='api-tasks'),
    path('api/tasks2', views.TaskList.as_view(), name="api-task-list"),
    path('api/tasks2/<pk>', views.TaskDetail.as_view()),

]


urlpatterns = format_suffix_patterns(urlpatterns)

JKTasks/views.py
from django.shortcuts import render
import logging

logger = logging.getLogger(__name__)
# Create your views here.

def index(request):
    """
    Home page view
    """
    
    return render(request, 'JKTasks/index.html')

JKTasks/templates/JKTasks/index.html
{% extends 'JKTasks/base.html' %}

{% block content %}
<div><a href="{% url 'Tasks:home' %}">Tasks home</a></div>
{% endblock %}

JKTasks/templates/JKTasks/login.html
{% extends "base.html" %}

{% block content %}
<h1 class="form-heading">login Form</h1>
<div class="login-form">
<div class="main-div">
    <div class="panel">
   <h2>Admin Login</h2>
   <p>Please enter your email and password</p>
</div>
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form id="Login" method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}

<p><a href="{% url 'password_reset' %}">Lost password?</a></p>
</div>
</div>

{% endblock %}