JKTasks/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views
from rest_framework import routers
app_name = "JKTasks"
urlpatterns = [
    path('', include('Tasks.urls')),
    path('tasks/', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='JKTasks/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('bot/', include('Telebot.urls')),
    path('cd/', include('countdown.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

Tasks/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "Tasks"
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^new-task/$', views.new_task, name='new_task'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<task_type>/', views.tasks, name='tasks'),
    path('task/<task_id>', views.task, name='task'),
    path('task/delete/<task_id>', views.task_delete, name='task_delete'),
    path('notes/', views.notes, name='notes'),
    path('notes/new', views.new_note, name='new_note'),
    path('notes/<note_id>', views.note, name='note'),
    path('manage/', views.task_management, name='task_management'),
    path('temp/', views.temp, name='temp'),
    path('temp_data/', views.temp_data, name='temp_data'),
    path('api/tasks', views.TaskViewSet.as_view({'get': 'list'}), name='api-tasks'),
    path('api/tasks2', views.TaskList.as_view(), name="api-task-list"),
    path('api/tasks2/<pk>', views.TaskDetail.as_view()),

]


urlpatterns = format_suffix_patterns(urlpatterns)

countdown/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

app_name = "countdown"
urlpatterns = [
    url(r'^$', views.index, name='home'),
    path("countdown/", views.countdown, name='countdown'),
    path("countdown/test/<pk>", views.countdown_detail, name='countdown_detail'),
    path("countdown/<cd_id>", views.send_countdown, name='countdown_send'),

]

countdown/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
import uuid
from django.contrib.auth.models import User

# Create your models here.
class Countdown(models.Model):
    """
    General countdown model
    """

    countdown_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    countdown_to = models.DateTimeField()
    created_by = models.ForeignKey('auth.User', null=True, blank=True, on_delete=models.SET_NULL)\
    
    def __str__(self):
        return self.title

countdown/forms.py
from django import forms
from django.forms import formset_factory
from django.db.models import Q
from .models import Countdown

class DateInput(forms.DateTimeInput):
    input_type = 'datetime-local'

class CountdownModelForm(forms.ModelForm):

    class Meta:
        model = Countdown
        fields = ['title', 'countdown_to']

        widgets = {
            'countdown_to': forms.DateInput(attrs={'class':'datepicker'}),
        }
class NewCountdownForm(forms.Form):
    title= forms.CharField(max_length=100)
    countdown_to_date = forms.SplitDateTimeField(widget=DateInput())
    countdown_to_time_value = forms.CharField(max_length=5)
    countdown_to_time_type = forms.ChoiceField(choices=((1, 'minute(-s)'), (2, 'hour(-s)'), (3, 'day(-s)'), (4, 'month(-s)'), (5, 'year(-s)')))

countdown/views.py
from django.shortcuts import render
from django.utils import timezone
from datetime import datetime, timedelta
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers

import json

from .forms import NewCountdownForm, CountdownModelForm
from .models import Countdown

import logging

logger = logging.getLogger('django')

def index(request):
    # Home page view: list of countdowns and a form to create a new one

    if request.method == 'POST':
        form = CountdownModelForm(request.POST)
        if form.is_valid():
            logger.info("form is valid")
            countdown = form.save(commit=False)
            countdown.created_by = request.user
            countdown.save()
    else:
        form = CountdownModelForm()
    countdowns = Countdown.objects.all()
    return render(request, 'home.html', {'form': form, 'countdowns': countdowns})

def countdown(request, delta=10):
    pk = "6d81ec95-9bcc-4bac-8398-ed0160441ba1"
    utc_offset = timedelta(hours=3)
    count_to = timezone.now() + timedelta(hours=10) #timezone
    count_to = datetime.now() + utc_offset #local
    count_to = datetime.now() + utc_offset + timedelta(minutes=delta) # actual countdown
    count_to = count_to.strftime("%b %d,  %Y %H:%M:%S")
    return render(request, 'countdown.html', {'count_to': count_to, "pk": pk})

def countdown_detail(request, pk):
    # Coundown by primary key
    utc_offset = timedelta(hours=3)
    c_pk = "fb3b96ae-38c2-42b1-a8ca-7ab63af5b061"
    count_to = datetime.now() + utc_offset + timedelta(minutes=10) # actual countdown
    count_to = count_to.strftime("%b %d,  %Y %H:%M:%S")
    countdown = Countdown.objects.get(countdown_id=pk)

    return render(request, 'countdown.html', {'count_to': count_to, "pk": pk, "countdown": countdown})
def send_countdown(request, cd_id):
    """
    Return countdown in json-format
    """

    countdown = Countdown.objects.get(countdown_id=cd_id)
    serialized_countdown = json.loads(serializers.serialize('json', [countdown, ]))
    #serialized_countdown[0]['fields']['countdown_to'] = "Jan 5, 2019 15:37:25"

    return JsonResponse(serialized_countdown, safe=False)

countdown/templates/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>JK Tasks app</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">      
        <link rel="shortcut icon" type="image/png" href="{% static '/favicon.ico'%}"/>
        <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
        <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
        <!-- Fonts -->
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Abril+Fatface&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Merriweather&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <!-- Losal stylesheets -->
        <link rel="stylesheet" type="text/css" href="{% static 'countdown/style.css' %}">
    </head>
<body>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
                </div>
        {% endfor %}
        </ul>
    {% endif %}

    <div class="content container">
            {% block content %}
            {% endblock %}
    </div>

</body>
</html>

countdown/templates/countdown.html
{% extends 'base.html' %}

{% block content %}
<style>
  p{
    color: white;
    text-align: center;
  }
  .panel{
    background-color: black;
  }
  .countdown{
    font-family: "Courier New", Courier, monospace;
    font-size: 30px;
    letter-spacing: 2px;
    word-spacing: 2px;
    font-weight: normal;
    text-decoration: none;
    font-style: normal;
    font-variant: normal;
    text-transform: none;
      }
</style>
<!-- Display the countdown timer in an element -->
<div class="panel">
<p>Countdown to {{ countdown }}.</p>
<p id="demo" class="countdown"></p>
<p id="countdown"></p>
</div>

<script>
// Display countdown info
var d;
function getMyTime(){
    $.ajax({
               type: 'GET',
               url: '{% url "countdown:countdown_send" cd_id=pk %}',
               processData: true,
               dataType: 'json',
               contentType: "application/json",
               success: function(data ) {
                                    d = data[0].fields.countdown_to
                                    console.log(data[0].fields);
                                    $('#countdown').text(data[0].fields.countdown_to);
                                    
                                    }
               });
    }
getMyTime();

// Set the date we're counting down to
//var countDownDate = new Date("Jan 5, 2019 15:37:25").getTime();
//var countDownDate = new Date("{{ count_to }}").getTime();
var countDownDate = new Date(d).getTime();
// Update the count down every 1 second
var x = setInterval(function() {
  var countDownDate = new Date(d).getTime();
  // Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h : "
  + minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text 
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>
{% endblock %}

countdown/templates/home.html
{% extends 'base.html' %}

{% block content %}
<script>
    $(function() {
      $( ".datepicker" ).datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
<div style="position: relative">
<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
</div>
<div class="list">
  <ul>
  {% for c in countdowns %}
    <li>
      <a href="{% url 'countdown:countdown_detail' pk=c.countdown_id %}">{{ c }}</a>
    </li>
  </ul>
  {% endfor %}
</div>
{% endblock %}