JKTasks/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from . import views
from rest_framework import routers
app_name = "JKTasks"
urlpatterns = [
    path('', include('Tasks.urls')),
    path('tasks/', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='JKTasks/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('bot/', include('Telebot.urls')),
    path('cd/', include('countdown.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

Tasks/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "Tasks"
urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^new-task/$', views.new_task, name='new_task'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<task_type>/', views.tasks, name='tasks'),
    path('task/<task_id>', views.task, name='task'),
    path('task/delete/<task_id>', views.task_delete, name='task_delete'),
    path('notes/', views.notes, name='notes'),
    path('notes/new', views.new_note, name='new_note'),
    path('notes/<note_id>', views.note, name='note'),
    path('manage/', views.task_management, name='task_management'),
    path('temp/', views.temp, name='temp'),
    path('temp_data/', views.temp_data, name='temp_data'),
    path('api/tasks', views.TaskViewSet.as_view({'get': 'list'}), name='api-tasks'),
    path('api/tasks2', views.TaskList.as_view(), name="api-task-list"),
    path('api/tasks2/<pk>', views.TaskDetail.as_view()),

]


urlpatterns = format_suffix_patterns(urlpatterns)

Tasks/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
import uuid
from django.contrib.auth.models import User
from Telebot.models import Bot_user
from django.conf import settings
# Create your models here.

class Task(models.Model):
    """
    General task model
    """

    task_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200, unique=False)
    description = models.CharField(max_length=200, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    finish_date = models.DateField(default=datetime.now, null=True, blank=True)
    created_by = models.ForeignKey('auth.User', null=True, blank=True, on_delete=models.SET_NULL)
    created_by_bot = models.ForeignKey(Bot_user, null=True, blank=True, on_delete=models.SET_NULL)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return "{0} | {1} [{2}]".format(self.title, self.start_date, self.completed)

class Note(models.Model):
    """
    General note model
    """

    note_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200, null=True, blank=True, default=" ")
    description = models.TextField(max_length=600, blank=True, null=True)
    created_date = models.DateField(null=True, blank=True)
    created_by = models.ForeignKey('auth.User', null=True, blank=True, on_delete=models.SET_NULL)
    created_by_bot = models.ForeignKey(Bot_user, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):

        return "Note"

class MultiTask(models.Model):
    """
    Multitask model model
    """

    task_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200, unique=False)
    description = models.CharField(max_length=200, null=True, blank=True)
    tasks = models.ManyToManyField(Task)
    start_date = models.DateField(null=True, blank=True)
    finish_date = models.DateField(default=datetime.now, null=True, blank=True)
    created_by = models.ForeignKey('auth.User', null=True, blank=True, on_delete=models.SET_NULL)
    created_by_bot = models.ForeignKey(Bot_user, null=True, blank=True, on_delete=models.SET_NULL)
    completed = models.BooleanField(default=False)

Tasks/forms.py
from django import forms
from django.forms import formset_factory
from django.db.models import Q
from .models import Task, Note

class DateInput(forms.DateInput):
    input_type = 'date'

class NewTaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['title', 'description', 'start_date']
        widgets = {
            'made_on': DateInput(),
        }

class NewNoteForm(forms.ModelForm):

    class Meta:
        model = Note
        fields = ['title', 'description', 'created_date']
        widgets = {
            'created_date': DateInput(),
        }
from django.forms import modelformset_factory

TaskModelFormset = modelformset_factory(
    Task,
    fields=['title', 'description', 'start_date', ],
    extra=1,
    widgets={'title': forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Task Name here'
        }),
        'start_date': DateInput(),
    }
)

Tasks/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from rest_framework import viewsets
from django.views.generic import TemplateView, View

from .models import *
from .forms import NewTaskForm, TaskModelFormset, NewNoteForm

#DRF portion of imports
from rest_framework import status, renderers
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import mixins
from rest_framework import generics
from .serializers import TaskSerializer, StandardTaskSerializer


from datetime import datetime, timedelta
import os

import logging

logger = logging.getLogger('django')
# Create your views here.

@login_required
def index(request):
    """
    Home page
    """
    tasks = Task.objects.filter(created_by=request.user, completed=False, start_date__gte=datetime.now().date()).order_by('start_date')
    past_tasks = Task.objects.filter(created_by=request.user, start_date__lt=datetime.now().date()) 

    return render(request, 'Tasks/index.html', {'tasks': tasks, 'past_tasks': past_tasks})

@login_required
def new_task(request):
    """
    View for creaing new tasks
    """
    template_name = 'Tasks/newtask.html'
    heading_message = 'Add New Tasks'
    if request.method == 'GET':
        # we don't want to display the already saved model instances
        formset = TaskModelFormset(queryset=Task.objects.none())
    elif request.method == 'POST':
        formset = TaskModelFormset(request.POST)
        if formset.is_valid():
            logger.info(len(formset))
            for form in formset:
                if form.is_valid():
                    if form.cleaned_data.get('title'):
                        task = form.save(commit=False)
                        task.created_by = request.user
                        task.finish_date = task.start_date + timedelta(days=10)
                        task.save()
                        logger.info(task)
                else:
                    logger.error("Form is invalid! %s" % form)
            messages.info(request, 'Task(-s) created by {0}.'.format(request.user))
            return redirect('Tasks:home')
    return render(request, template_name, {
            'formset': formset,
            'heading': heading_message,
        })

@login_required
def notes(request):
    """
    List notes view
    """

    notes = Note.objects.filter(created_by=request.user)

    return render(request, 'Notes/notes.html', {'notes': notes})

@login_required
def note(reqest, note_id):
    """
    Note detail view
    """

    note = Note.objects.get(note_id=note_id)

    return render(reqest, 'Notes/note-detail.html', {'note': note})

@login_required
def new_note(request):
    """
    View for creating new notes
    """

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NewNoteForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            logger.info("form is valid")
            note = form.save(commit=False)
            note.created_by = request.user
            note.save()

            messages.info(request, 'Note(-s) created by {0}.'.format(request.user))
            return redirect('/')
        else:
            logger.error("form is invalid")
            messages.error(request, 'FORM INVALID')
            return redirect('Tasks:new_note')

    else:
        form = NewNoteForm()

    return render(request, 'Notes/newnote.html', {'form': form})

def temp(request):
    template_name = 'Tasks/temp.html'
    context = {

    }
    return render(request, template_name)
    #return redirect('Tasks:home')

def temp_data(request):
    task_num = len(Task.objects.all())

    return JsonResponse({'tasks':task_num})

@login_required
def task_management(request):
    """
    View for creaing new tasks
    """
    tasks = Task.objects.filter(created_by=request.user, completed=False, finish_date__gte=datetime.now().date()).order_by('start_date')

    if request.method == "POST":
        logger.info(request.POST)
        ids_complete = request.POST.getlist('complete', '')
        for task_id in ids_complete:        
            if task_id != '':
                task = Task.objects.get(task_id=task_id)
                task.completed = True
                task.save()


    return render(request, 'Tasks/manage.html', {'tasks': tasks})

@login_required
def tasks(request, task_type='all'):
    """
    Tasks list by type
    """

    if task_type == 'past':
        tasks = Task.objects.filter(created_by=request.user, finish_date__lte=datetime.now().date())
    elif task_type == 'active':
        tasks = Task.objects.filter(created_by=request.user, completed=False, finish_date__gte=datetime.now().date()).order_by('start_date')
    elif task_type == 'missed':
        tasks = Task.objects.filter(created_by=request.user, finish_date__lte=datetime.now().date(), completed=False)
    elif task_type == 'future':
        tasks = Task.objects.filter(created_by=request.user, start_date__gte=datetime.now().date(), completed=False)
    else:
        tasks = Task.objects.filter(created_by=request.user)

    return render(request, 'Tasks/tasks.html', {'tasks': tasks, 'task_type': task_type})


@login_required
def task(request, task_id):
    """
    Individual task page
    """
    task = Task.objects.get(task_id=task_id)

    return render(request, 'Tasks/task-detail.html', {'task': task})

@login_required
def task_delete(request, task_id):
    task = Task.objects.get(task_id=task_id)
    task.delete()
    messages.info(request, 'Task was deleted.')
    #redirect to prev. page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

class TaskViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows tasks to be viewed or edited.
    """
    queryset = Task.objects.all().order_by('-start_date')
    serializer_class = TaskSerializer
    renderer_classes = [renderers.JSONRenderer]

    def perform_create(self, serializer):
        """Save the post data when creating a new bucketlist."""
        serializer.save()

class TaskList(mixins.ListModelMixin,
                  mixins.CreateModelMixin,
                  generics.GenericAPIView):

    queryset = Task.objects.all()
    serializer_class = TaskSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

class TaskDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

Tasks/templates/Tasks/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>JK Tasks app</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">      
        <link rel="shortcut icon" type="image/png" href="{% static '/favicon.ico'%}"/>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->     
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://use.fontawesome.com/ad4f6e3394.js"></script>
        <!-- Fonts -->
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Abril+Fatface&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Merriweather&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <!-- Local scripts-->
        <script src="{% static 'Tasks/scripts/scripts.js' %}"></script>
        <!-- Losal stylesheets -->
        <link rel="stylesheet" type="text/css" href="{% static 'Tasks/css/base.css' %}">
    </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link {% if request.resolver_match.url_name == 'home' %} active {% endif %}" href="{% url 'Tasks:home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'Tasks:tasks' %}">Tasks</a>
                <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'Tasks:new_task' %}">New Task</a>
                <a class="dropdown-item" href="{% url 'Tasks:tasks' task_type='active' %}">Active</a>
                <a class="dropdown-item" href="{% url 'Tasks:tasks' task_type='future' %}">Future</a>
                <a class="dropdown-item" href="{% url 'Tasks:tasks' task_type='past' %}">Past</a>
                <a class="dropdown-item" href="{% url 'Tasks:tasks' task_type='missed' %}">Missed</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="{% url 'Tasks:notes' %}">Notes</a>
                <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'Tasks:new_note' %}">New Note</a>
                <a class="dropdown-item" href="{% url 'Tasks:notes' %}">List all notes</a>
                </div>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'Tasks:task_management' %}">Task Management</a>
                </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Countdowns</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>

          </ul>
          <form class="form-inline my-2 my-lg-0">
            {% if user.is_authenticated %}
            <p class="navbar-text">Hello, {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            <button class="nav-item btn"><a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-edit"></span>Control panel</a></button> 
            {% else %}
            <button class="btn"><a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-lock"></span>Login</a></button>
            {% endif %}
            </form>
        </div>
      </nav>
<div>
        <form id="Login" class="form-horizontal" method="post" action="{% url 'login' %}">
                {% csrf_token %}
                <table>
                <tr>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password }}</td>
                </tr>
                </table>
                
                <input type="submit" value="login">
                <input type="hidden" name="next" value="{{ next }}">
                </form>
</div>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
                </div>
        {% endfor %}
        </ul>
    {% endif %}
 
    <div class="content container">
            {% block content %}
            {% endblock %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

Tasks/templates/Tasks/index.html
{% extends 'Tasks/base.html' %}

{% block content %}
    <h2>Your task to complete:</h2>
    <div>
        {% for task in tasks %}
        <p class="task">
            <a href="{% url 'Tasks:task' task_id=task.task_id %}">{{ task }}</a>
        </p>
        {% endfor %}
    </div>
    <h3>Past tasks:</h3>
    <div>
        {% for task in past_tasks %}
        <p class="task">
            <a href="{% url 'Tasks:task' task_id=task.task_id %}">{{ task }}</a>
        <span style="{% if task.completed == True %} background-color:#45f442 {% endif %};" id="colorbox"></span>
        </p>
        {% endfor %}
    </div>
    <hr>
    <a href='{% url "Tasks:new_task" %}'><button type="button" class="btn btn-light">Create new task</button></a>
    
    
{% endblock %}

Tasks/templates/Tasks/manage.html
{% extends 'Tasks/base.html' %}

{% block content %}
<script>
    function confirmed(b, task_id){
        event.preventDefault();
        var result = confirm("Want to delete?");
        if (result) {
            console.log(task_id)
            //Logic to delete the item
            window.location.href = b.getAttribute('href');
        }
    }
    </script>
<div class="form manage">
        <h2>Complete your tasks:</h2>
        
        <p>
        <form  id="taskForm" method="POST"> {% csrf_token %}
            {% for task in tasks%}
            <label name ="task" style="font-weight: bold;" value="{{ task.task_id }}" >{{ task.title }}: {{ task.description }}</label><br>
            <label name="start_on">Stated(-s) on: {{ task.start_date }}</label><br>    
            <label name="complete_by">Complete by: {{ task.finish_date }}</label><br> 
            <label class="checkbox-container"> - completed <input type="checkbox" name="complete" value="{{ task.task_id }}">
            <span class="checkmark"></span>
            </label>
            <a href="{% url 'Tasks:task_delete' task_id=task.task_id %}" type="button" onclick="confirmed(this, '{{ task.task_id }}')" class="btn btn-danger">Delete</a>  
            <hr>
            {% endfor %}  
            <input type="submit" class="btn btn-light" value="Confirm">         
        </form>
        </p>

</div>
<hr>

{% endblock %}

Tasks/templates/Tasks/newtask.html
{% extends 'Tasks/base.html' %}

{% block content %}
  <script>
    $( function() {
        $( "#id_start_date" ).datepicker();
    } );
  </script>
    <div>
        <h2>Create new tasks:</h2>
        <form class="form-horizontal" method="POST" action="">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
            <div class="row form-row">
                    <div class="input-group">
                        {{form.as_table }}
                        <div class="input-group-append">
                                <button name="form-0-button" class="btn btn-success add-form-row">+</button>
                            </div>
                            <hr>
                    </div>
            </div>
            {% endfor %}
            <div class="row">
                    <button type="submit" class="btn btn-light">Create</button>
            </div>
        </form>
    </div>
    <script type='text/javascript'>
        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }
        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            console.log('Repalcing...')
            newElement.find(':input').each(function() {
                console.log($(this))
                var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');

                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            var conditionRow = $('.form-row:not(:last)');
            conditionRow.find('.btn.add-form-row')
            .removeClass('btn-success').addClass('btn-danger')
            .removeClass('add-form-row').addClass('remove-form-row')
            .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>');
            return false;
        }
        function deleteForm(prefix, btn) {
            var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
            }
            return false;
        }
        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });
    </script>
{% endblock %}

Tasks/templates/Tasks/task-detail.html
{% extends 'Tasks/base.html' %}

{% block content %}
    <a href='{% url "Tasks:new_task" %}'>Create new task</a>
    <h2>Task: {{ task.title }}</h2>
    <p>{{ task.description }}</p>
    <p>Created on {{ task.start_date }} by {{ task.created_by }}.</p>
    <p>Needed to be completed by {{ task.finish_date }}. </p>
    <p>Task is {% if task.completed == False %}NOT{% endif %} completed.</p>

{% endblock %}

Tasks/templates/Tasks/tasks.html
{% extends 'Tasks/base.html' %}

{% block content %}
    <div>
        <h2>Your {{ task_type }} tasks:</h2>
        {% for task in tasks %}
            <p><a href="{% url 'Tasks:task' task_id=task.task_id %}">{{ task }}</a></p>
        {% endfor %}
        <hr>
        <a href='{% url "Tasks:new_task" %}'><button type="button" class="btn btn-light">Create new task</button></a>
    </div>

{% endblock %}

Tasks/templates/Tasks/temp.html
{% extends 'Tasks/base.html' %}

{% block content %}

<script>
var interval = 20000;
setInterval(function(){
    $.ajax({
               type: 'GET',
               url: '{% url "Tasks:api-tasks" %}',
               processData: true,
               dataType: 'json',
               contentType: "application/json",
               success: function(data ) {

                                    console.log(data)
                                    $('.status').text("Tasks number: " + data.length)


                                    }
               });
    }, interval);
  </script>
  <div class="status">

  </div>

{% endblock %}